# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title/
relative_permalinks: true

# Setup
title:               Dan Newman
tagline:             ''
description:         ''
baseurl:             /
paginate:            5
paginate_path:       "/my-blog/page:num/"

# About/contact
author:
  name:              Dan Newman
  url:               http://dpnewman.com

# Excludes
exclude: [".editorconfig", ".gitignore", "CNAME", "Gemfile", "Gemfile.lock", "README.md"]
