# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title/


# Setup
title:               Daniel P Newman
tagline:             ''
description:         'personal website and blog of Daniel P. Newman'
baseurl:             ''
paginate:            5
paginate_path:       "/my-blog/page:num/"

# Google services
google_analytics: UA-86175629-1

# About/contact
author:
  name:              Daniel P Newman
  url:               http://dpnewman.com
  

# Excludes
exclude: [".editorconfig", ".gitignore", "CNAME", "Gemfile", "Gemfile.lock", "README.md"]

