# Dependencies
markdown:            kramdown

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title/


# Setup
title:               Daniel P Newman
tagline:             ''
description:         'personal website and blog for a data scientist, neuroscientist and investment enthusiast'
baseurl:             ''
paginate:            5
paginate_path:       "/my-blog/page:num/"


# About/contact
author:
  name:              Daniel P Newman
  url:               http://dpnewman.com


# Excludes
exclude: [".editorconfig", ".gitignore", "CNAME", "Gemfile", "Gemfile.lock", "README.md"]

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate


kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
